export const BoxDrawingChars = {
  "Light Horizontal": "─",
  "Heavy Horizontal": "━",
  "Light Vertical": "│",
  "Heavy Vertical": "┃",
  "Light Triple Dash Horizontal": "┄",
  "Heavy Triple Dash Horizontal": "┅",
  "Light Triple Dash Vertical": "┆",
  "Heavy Triple Dash Vertical": "┇",
  "Light Quadruple Dash Horizontal": "┈",
  "Heavy Quadruple Dash Horizontal": "┉",
  "Light Quadruple Dash Vertical": "┊",
  "Heavy Quadruple Dash Vertical": "┋",
  "Light Down and Right": "┌",
  "Down Light and Right Heavy": "┍",
  "Down Heavy and Right Light": "┎",
  "Heavy Down and Right": "┏",
  "Light Down and Left": "┐",
  "Down Light and Left Heavy": "┑",
  "Down Heavy and Left Light": "┒",
  "Heavy Down and Left": "┓",
  "Light Up and Right": "└",
  "Up Light and Right Heavy": "┕",
  "Up Heavy and Right Light": "┖",
  "Heavy Up and Right": "┗",
  "Light Up and Left": "┘",
  "Up Light and Left Heavy": "┙",
  "Up Heavy and Left Light": "┚",
  "Heavy Up and Left": "┛",
  "Light Vertical and Right": "├",
  "Vertical Light and Right Heavy": "┝",
  "Up Heavy and Right Down Light": "┞",
  "Down Heavy and Right Up Light": "┟",
  "Vertical Heavy and Right Light": "┠",
  "Down Light and Right Up Heavy": "┡",
  "Up Light and Right Down Heavy": "┢",
  "Heavy Vertical and Right": "┣",
  "Light Vertical and Left": "┤",
  "Vertical Light and Left Heavy": "┥",
  "Up Heavy and Left Down Light": "┦",
  "Down Heavy and Left Up Light": "┧",
  "Vertical Heavy and Left Light": "┨",
  "Down Light and Left Up Heavy": "┩",
  "Up Light and Left Down Heavy": "┪",
  "Heavy Vertical and Left": "┫",
  "Light Down and Horizontal": "┬",
  "Left Heavy and Right Down Light": "┭",
  "Right Heavy and Left Down Light": "┮",
  "Down Light and Horizontal Heavy": "┯",
  "Down Heavy and Horizontal Light": "┰",
  "Right Light and Left Down Heavy": "┱",
  "Left Light and Right Down Heavy": "┲",
  "Heavy Down and Horizontal": "┳",
  "Light Up and Horizontal": "┴",
  "Left Heavy and Right Up Light": "┵",
  "Right Heavy and Left Up Light": "┶",
  "Up Light and Horizontal Heavy": "┷",
  "Up Heavy and Horizontal Light": "┸",
  "Right Light and Left Up Heavy": "┹",
  "Left Light and Right Up Heavy": "┺",
  "Heavy Up and Horizontal": "┻",
  "Light Vertical and Horizontal": "┼",
  "Left Heavy and Right Vertical Light": "┽",
  "Right Heavy and Left Vertical Light": "┾",
  "Vertical Light and Horizontal Heavy": "┿",
  "Up Heavy and Down Horizontal Light": "╀",
  "Down Heavy and Up Horizontal Light": "╁",
  "Vertical Heavy and Horizontal Light": "╂",
  "Left Up Heavy and Right Down Light": "╃",
  "Right Up Heavy and Left Down Light": "╄",
  "Left Down Heavy and Right Up Light": "╅",
  "Right Down Heavy and Left Up Light": "╆",
  "Down Light and Up Horizontal Heavy": "╇",
  "Up Light and Down Horizontal Heavy": "╈",
  "Right Light and Left Vertical Heavy": "╉",
  "Left Light and Right Vertical Heavy": "╊",
  "Heavy Vertical and Horizontal": "╋",
  "Light Double Dash Horizontal": "╌",
  "Heavy Double Dash Horizontal": "╍",
  "Light Double Dash Vertical": "╎",
  "Heavy Double Dash Vertical": "╏",
  "Double Horizontal": "═",
  "Double Vertical": "║",
  "Down Single and Right Double": "╒",
  "Down Double and Right Single": "╓",
  "Double Down and Right": "╔",
  "Down Single and Left Double": "╕",
  "Down Double and Left Single": "╖",
  "Double Down and Left": "╗",
  "Up Single and Right Double": "╘",
  "Up Double and Right Single": "╙",
  "Double Up and Right": "╚",
  "Up Single and Left Double": "╛",
  "Up Double and Left Single": "╜",
  "Double Up and Left": "╝",
  "Vertical Single and Right Double": "╞",
  "Vertical Double and Right Single": "╟",
  "Double Vertical and Right": "╠",
  "Vertical Single and Left Double": "╡",
  "Vertical Double and Left Single": "╢",
  "Double Vertical and Left": "╣",
  "Down Single and Horizontal Double": "╤",
  "Down Double and Horizontal Single": "╥",
  "Double Down and Horizontal": "╦",
  "Up Single and Horizontal Double": "╧",
  "Up Double and Horizontal Single": "╨",
  "Double Up and Horizontal": "╩",
  "Vertical Single and Horizontal Double": "╪",
  "Vertical Double and Horizontal Single": "╫",
  "Double Vertical and Horizontal": "╬",
  "Light Arc Down and Right": "╭",
  "Light Arc Down and Left": "╮",
  "Light Arc Up and Left": "╯",
  "Light Arc Up and Right": "╰",
  "Light Diagonal Upper Right to Lower Left": "╱",
  "Light Diagonal Upper Left to Lower Right": "╲",
  "Light Diagonal Cross": "╳",
  "Light Left": "╴",
  "Light Up": "╵",
  "Light Right": "╶",
  "Light Down": "╷",
  "Heavy Left": "╸",
  "Heavy Up": "╹",
  "Heavy Right": "╺",
  "Heavy Down": "╻",
  "Light Left and Heavy Right": "╼",
  "Light Up and Heavy Down": "╽",
  "Heavy Left and Light Right": "╾",
  "Heavy Up and Light Down": "╿",
}
